export { default as Button } from "./Button/Button";
export { default as Input } from "./Input/Input";
export { default as MainLayout } from "./Layouts/MainLayout";
export { default as Header } from "./Header/Header";
export { default as NewFactForm } from "./NewFactForm/NewFactForm";
export { default as Category } from "./Category/Category";
export { default as Fact } from "./Fact/Fact";
export { default as Loader } from "./Loader/Loader";
export { default as FactList } from "./FactList/FactList";
