import type { Metadata } from "next";
import Coiny from "next/font/local";
import Sono from "next/font/local";
import "./globals.css";

const coiny = Coiny({
  src: "./fonts/Coiny-Regular.ttf",
  display: "swap",
});

// const sonoMono = Sono({
//   src: "./fonts/Sono-VariableFont_MONO,wght.ttf",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${coiny.className} antialiased`}>{children}</body>
    </html>
  );
}
